### create category
POST http://localhost:8000/category/create-category
Content-Type: application/json

{
    "name":"figuras"
}

### get all category
GET http://localhost:8000/category/get

### get category by ID for query
GET http://localhost:8000/category/get/65d5548740c36abe29c885eb

### create subCategory
POST http://localhost:8000/category/create-subCategory
Content-Type: application/json

{
    "name":"comunion",
    "categoryId":"65d554a440c36abe29c885ed"
}

### get all subCategory
GET  http://localhost:8000/category/subCategory

### get subCategory by id
GET  http://localhost:8000/category/subCategory/65d558c840c36abe29c885f1

### get all subCategory by category
GET  http://localhost:8000/category/subCategoryByCategory/65d5548740c36abe29c885eb
