### get all products
GET http://localhost:8000/products/get


### get product by id - for param - OK 
GET http://localhost:8000/products/get/65d57a4dd1b3a2e0bfdd3bbc


### update available - ok
PATCH http://localhost:8000/products/available-product
Content-Type: application/json

{
    "id":"65d57afbd1b3a2e0bfdd3bc0",
    "available": true
}

### delete product by id
DELETE http://localhost:8000/products/delete/65e7cff9bf3f381ba405b5d1

### update etiquetas - ok [ofertas , novedades , destacados]
PATCH http://localhost:8000/products/etiquetas/patch
Content-Type: application/json

{
    "id":"65dfe52785b383a69904662e",
    "label": "ofertas"
}

### get product by etiqueta - for query - OK 
###ofertas
GET http://localhost:8000/products/etiquetas?label=ofertas

###novedades
GET http://localhost:8000/products/etiquetas?label=novedades

###destacados
GET http://localhost:8000/products/etiquetas?label=destacados

###destacados
GET http://localhost:8000/products/etiquetas?label=none
